export { default as IconPlus } from './IconPlus.vue'
export { default as IconMove } from './IconMove.vue'
export { default as IconCheck } from './IconCheck.vue'
export { default as IconMenu } from './IconMenu.vue'
export { default as IconAlive } from './IconAlive.vue'
export { default as IconStatusKilled } from './IconStatusKilled.vue'
export { default as IconStatusExecuted } from './IconStatusExecuted.vue'
